# Konfigurasi untuk Netlify Functions
[functions]
  # Memastikan semua file .html di dalam direktori fungsi
  # disertakan dalam paket deploy untuk setiap fungsi.
  # Ini akan menyelesaikan masalah "Could not load email template".
  included_files = ["netlify/functions/*.html"]
